### ISSUE TITLE
Does BOX64 works with WINE?

### ISSUE THREAD

**Issue by hongtm77** [cobalt2727/L4T-Megascript#103]
Hi all, thanks for the great project. Recently I have been searching on how to get WINE to work on arm64 and came across that BOX64 can be installed with l4t Megascript. After installing BOX64, I'm still not able to install WINE and seems like it requires i386 to work. Or did I got the wrong version of WINE?

**Comment by cobalt2727** [comment]
You may want to take this to https://github.com/ptitSeb/box64/issues
