### ISSUE TITLE
apt should not be used in scripts

### ISSUE THREAD

**Issue by leonpano2006** [cobalt2727/L4T-Megascript#105]
can you replace apt with apt-get in script?
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by cobalt2727** [comment]
If you encounter any issues that come up from using apt please send the log files

**Comment by leonpano2006** [comment]
(just replace apt with apt-get in scripts)

**Comment by cobalt2727** [comment]
If that comes up as a problem, we'll modify it as needed

Thanks for checking in though!

**Comment by leonpano2006** [comment]
(just replace apt with apt-get in scripts)
