### ISSUE TITLE
Wrong "if else" syntax

### ISSUE THREAD

**Issue by Archargelod** [cobalt2727/L4T-Megascript#107]
https://github.com/cobalt2727/L4T-Megascript/commit/c4d291000b6c1dd95b5cd7b587c0d64867b6115d

if there's nothing between "then" and "else", bash throws an syntax error, easy (dumb) fix would be to add a dummy code there.

e.g. 
```
if [[ $(echo $VERSION) == *"LTS"* ]]; then
		#echo "this is an LTS"
                echo ""
else
```
also, I don't think it's a good idea to always pull files from actively developed branch, where single commit can break everything.

**Comment by cobalt2727** [comment]
You're entirely right, I definitely had that in my local testing setup - must have forgotten to copy that into production. Thanks for the catch!
