### ISSUE TITLE
Infinite boot loop on Gnome desktop

### ISSUE THREAD

**Issue by AwesomeAurick** [cobalt2727/L4T-Megascript#113]
When installed the Gnome desktop via the installation script. I cannot boot into the gnome xorg or gnome classic.

**Comment by theofficialgman** [comment]
We have had a few of these reports via the discord.
Unfortunately it's not replicatable when I try myself and everything works as it should.

Given that gnome does not run well and there is this occasional issue on switch, I may just outright remove gnome from the megascript.

**Comment by AwesomeAurick** [comment]
have you tried replicating it with a fresh install?

**Comment by theofficialgman** [comment]
Yes, when I last tested a few months ago that is what I did

**Comment by cobalt2727** [comment]
> We have had a few of these reports via the discord.
> Unfortunately it's not replicatable when I try myself and everything works as it should.
> 
> Given that gnome does not run well and there is this occasional issue on switch, I may just outright remove gnome from the megascript.

No objections here.

**Comment by theofficialgman** [comment]
Sorry I realize that this isn't the solution you were hoping for.
However I can not replicate it and to keep other users from running into this it has been disabled in the GUI.

If at some point in the future a way to replicate is found and a solution is made, then it can be added back.

**Comment by cobalt2727** [comment]
I realize this isn't something we'll be able to test for a while, but I vote we re-enable it for everyone once azkali's 20.04 update script becomes mandatory (which I'd like to do effective June 2023 when 18.04's EoL hits).
Hopefully Gnome cooperates fine there...
