### ISSUE TITLE
Error on initial setup

### ISSUE THREAD

**Issue by ik1g19** [cobalt2727/L4T-Megascript#116]
Error message provides these details:
Your APT repos can not be updated and apt has exited with an error
Check the above terminal logs for any BROKEN apt repos that you may have added

These are the errors I've found in the log:
Err:14 http://gb.archive.ubuntu.com/ubuntu bionic/main arm64 Packages
  404  Not Found
Err:43 http://gb.archive.ubuntu.com/ubuntu bionic-updates/main arm64 Packages
  404  Not Found
Err:55 http://gb.archive.ubuntu.com/ubuntu bionic-backports/main arm64 Packages
  404  Not Found

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/bionic/main/binary-arm64/Packages  404  Not Found 
E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-arm64/Packages  404  Not Found 
E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/bionic-backports/main/binary-arm64/Packages  404  Not Found 
E: Some index files failed to download. They have been ignored, or old ones used instead.

Full error log:
[log.txt](https://github.com/cobalt2727/L4T-Megascript/files/10325798/log.txt)

**Comment by cobalt2727** [comment]
It's not a Megascript issue, something's funky with your apt repositories - could you post the output of `cat /etc/apt/sources.list` for me?

**Comment by ik1g19** [comment]
Sure - 

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://gb.archive.ubuntu.com/ubuntu/ bionic main restricted
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://gb.archive.ubuntu.com/ubuntu/ bionic universe
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic universe
deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates universe
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic multiverse
deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://gb.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://ports.ubuntu.com/ubuntu-ports/ bionic-security restricted main multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ bionic-security universe
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-security universe
# deb-src http://ports.ubuntu.com/ubuntu-ports/ bionic-security multiverse
deb http://gb.archive.ubuntu.com/ubuntu/ bionic universe restricted multiverse main
deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted universe multiverse
deb https://download.sublimetext.com/ apt/stable/
# deb-src https://download.sublimetext.com/ apt/stable/

**Comment by theofficialgman** [comment]
arm64 Ubuntu repo is ports.ubuntu.com and is not found in the default Ubuntu repositories. arm64, armhf, ppc64 and a few other architectures are in the ports repo
Why have you changed the repositories?

**Comment by ik1g19** [comment]
> arm64 Ubuntu repo is ports.ubuntu.com and is not found in the default Ubuntu repositories. arm64, armhf, ppc64 and a few other architectures are in the ports repo Why have you changed the repositories?

can't say I've made any changes, this is a fresh install of l4t ubuntu

**Comment by theofficialgman** [comment]
It's not a fresh install I can guarantee that.
Closing as a non issue. Make a fresh install from the official switchroot.org website

**Comment by cobalt2727** [comment]
That actually might not be necessary...

```bash
sudo apt install gedit && sudo gedit /etc/apt/sources.list
```

Then remove these lines you added at the end for whatever reason...
```
deb http://gb.archive.ubuntu.com/ubuntu/ bionic universe restricted multiverse main
deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted universe multiverse
deb https://download.sublimetext.com/ apt/stable/
# deb-src https://download.sublimetext.com/ apt/stable/
```

No guarantees though, I don't know what else you did to put this here. If it's still broken after that then yeah it's on you

**Comment by theofficialgman** [comment]
Nope, they will be missing a bunch of repos if the do that.  It's a bunch of random repos that were changed.

@ik1g19 if you are using this on a Nintendo switch, only use official images from switchroot.
If you are using a Nvidia Jetson, only use official images from Nvidia's website
