### ISSUE TITLE
RetroPie back button hotkey not working on L4T 5.0.0 update

### ISSUE THREAD

**Issue by hongtm77** [cobalt2727/L4T-Megascript#117]
After updated to L4T Ubuntu 5.0.0, the back button on Retropie not working. Tried to re configure the input still not working. Cannot go back to Retropie main menu anymore after entering any system.

**Comment by theofficialgman** [comment]
What controller are you using? Note that you shouldn't use the capture button as that is enable/disable for mouse/keyboard input

**Comment by hongtm77** [comment]
> What controller are you using? Note that you shouldn't use the capture button as that is enable/disable for mouse/keyboard input. What is your "back" button? Exiting RetroArch is a two button process. Pressing the hotkey button and X at the same time

I'm using joycon. Previously on 3.4.0 working fine. I set home button as back button. I tried to set other button to test but not working as well

**Comment by theofficialgman** [comment]
there is no back button, idk what you mean. emulationstation has you map a "hotkey" button. you press that button in addition to your X button to exit retroarch emulators

**Comment by hongtm77** [comment]
I see, I did not know that. Will try later. Because previously I only press the hotkey button and I go back to the main menu 🤔

**Comment by theofficialgman** [comment]
Sorry hotkey plus start button. Not x.
Refer to RetroPie documentation, scroll down till you get to hotkey https://retropie.org.uk/docs/First-Installation/

**Comment by hongtm77** [comment]
> Sorry hotkey plus start button. Not x.
> 
> Refer to RetroPie documentation, scroll down till you get to hotkey https://retropie.org.uk/docs/First-Installation/

Okay, thank you so much, tested and it works.
