### ISSUE TITLE
the Chinese government blocks raw.githubusercontent.com, breaking the Megascript

### ISSUE THREAD

**Issue by ztyjason** [cobalt2727/L4T-Megascript#118]
hello,I from china
my English is bad
i want install box64，but i can't open Megascript in the APP list.
my device is Nintendo switch, OS is switchroot Ubuntu 5.0.0
thank you for solve

**Comment by cobalt2727** [comment]
What happens when you try to open the Megascript from the app list?

If I remember correctly, China blocks https://raw.githubusercontent.com, so you might need to set up a VPN to use the Megascript...

**Comment by ztyjason** [comment]
megascript’s  window flickers and then closes

**Comment by cobalt2727** [comment]
> you might need to set up a VPN to use the Megascript...

Let's see if my guess is correct. Can you tell me what happens when you type this in a terminal? 

```bash
bash <( wget -O - https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/core_refactor2.sh ) "gui"
```

This command runs the app, and should show you error logs.

**Comment by ztyjason** [comment]
https://ibb.co/D1QHCxt

**Comment by theofficialgman** [comment]
please send the contents of `wget-log` from the folder you ran the command in. regardless I belive cobalt is correct and your great firewall is blocking you access to the wider internet.

also in the future run it so that we can read it in english like follows:
```
add_english() { # add en_US locale for more accurate error
  if [ "$(cat /usr/share/i18n/SUPPORTED | grep -o 'en_US.UTF-8')" == "en_US.UTF-8" ]; then
    locale=$(locale -a | grep -oF 'en_US.utf8')
    if [ "$locale" != 'en_US.utf8' ]; then
      status "Adding en_US locale for better logging... "
      sudo sed -i '/en_US.UTF-8/s/^#[ ]//g' /etc/locale.gen
      sudo locale-gen
    fi
  else
    warning "en_US locale is not available on your system. This may cause bad logging experience."
  fi
  export LANG="en_US.UTF-8"
  export LANGUAGE="en_US.UTF-8"
  export LC_ALL="en_US.UTF-8"
}
add_english

bash <( wget -O - https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/core_refactor2.sh ) "gui"
```

**Comment by cobalt2727** [comment]
I would suggest setting up a VPN - this will allow you to properly use the Megascript without government censors.

**Comment by Hvliam** [comment]
please join QQ群：620438502

**Comment by cobalt2727** [comment]
@Hvliam I have deleted your comment. Do not advertise unrelated junk. This is your only warning. Users needing support can file an Issue report here or use the 3 Discord servers run by us or the Switchroot team.
