### ISSUE TITLE
Why is there no license on the repo?

### ISSUE THREAD

**Issue by Miepee** [cobalt2727/L4T-Megascript#122]
This project is missing a license. This means that by default all code in this repo is under exclusive copyright, with no one being able to copy, distribute, or modify it without risking legal actions.
See https://choosealicense.com/no-permission/ for more info.

This repo once had a license in the past (GPLv3), but I'm not sure why it was removed. 
It's also worth noting that (re)licensing a project requires consent from all contributors, or rewrite the code from contributors that don't give consent.

**Comment by Miepee** [comment]
> however this does not mean the code isn't open source. github's TOS allows all code plublished as public to be forked and viewed.

Open source is not the same as source available. The megascripts currently fit the definitions for the latter, but not the first.

> (99% of the existing lines have been written by us) so only we need to decide

IANAL but to my knowledge, even if there is a 1% that wrote code, those people still need to give consent (unless the whole thing was rewritten). Better be safe than sorry with legal stuff.

> I would also argue that you can't really license install scripts anyway

From what I've seen of the install scripts at least, almost all are modified enough in a way that isn't a direct copy of someone's documentation and thus could benefit form a license. Although it is true that simple stuff like cmake callings are a bit weird to license.

**Comment by theofficialgman** [comment]
> From what I've seen of the install scripts at least, almost all are modified enough in a way that isn't a direct copy of someone's documentation and thus could benefit form a license.

no not really. most scripts are a direct copy with a bit of error checking sprinkled in. hardly anything worth or able to be licensed

> IANAL but to my knowledge, even if there is a 1% that wrote code, those people still need to give consent (unless the whole thing was rewritten). Better be safe than sorry with legal stuff.

thats no big deal. only a maximum of maybe 100 lines of bash scripting is written by other contributors. I can rewrite those in an evening and already plan to do so for some scripts anyway. 

https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/games_and_emulators/SRB2.sh
https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/games_and_emulators/SRB2Kart.sh
https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/games_and_emulators/ST2.sh
https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/extras/antimicrox.sh

also we have contact with our contributors and there are not that many. it sholdn't be hard to get them to agree to a license if we decide on one.

**Comment by cobalt2727** [comment]
well this aged poorly
