### ISSUE TITLE
Box86 support

### ISSUE THREAD

**Issue by Tokobotenkai** [cobalt2727/L4T-Megascript#129]
Hi,

I was wondering if we can install Box86 as well on L4T?

https://gbatemp.net/threads/run-x86-apps-on-l4t-switch-with-box86.582933/

Looking at what was executed, it seems like we can manually build Box86 too?
```
git clone https://github.com/ptitSeb/box86

cd box86

mkdir build; cd build; cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo; make
```
I kinda see the rest of the steps are done but not sure if it would conflict with the existing Box64 installation and stuff.

Any ideas?

**Comment by theofficialgman** [comment]
box86 is already in the megascript but it isn't in the GUI because tegra devices do not have ARMhf gpu drivers necessary for hardware accelerated GPU rendering. so I don't want users to really use it outside of the steam script that properly configures steam to use virgl on launch
