### ISSUE TITLE
Citra: Compilation fails

### ISSUE THREAD

**Issue by PeterKnecht93** [cobalt2727/L4T-Megascript#139]
Hello again,
After running the Citra Installer through the Megascript, deleting the citra folder and re running both the Auto Updater and the Citra Script, It fails again, and, from what I can tell, with the same issue. Here`s the error and the generated Log File:

![20230618_213058](https://github.com/cobalt2727/L4T-Megascript/assets/129611251/51668740-bf38-4a14-8427-caa780396524)
[install-fail-Citra.log](https://github.com/cobalt2727/L4T-Megascript/files/11782469/install-fail-Citra.log)

**Comment by theofficialgman** [comment]
tell upstream to fix it then since they merged this 2 days ago https://github.com/citra-emu/citra/pull/6570

**Comment by PeterKnecht93** [comment]
Actually already filed an issue, I was told to delete the citra folder and then it should work, see citra-emu/citra#6624

**Comment by theofficialgman** [comment]
should be fixed upstream https://github.com/cobalt2727/L4T-Megascript/actions/runs/5327486628
