### ISSUE TITLE
Could not pull latest source code 

### ISSUE THREAD

**Issue by MeteoroidShot** [cobalt2727/L4T-Megascript#141]
I'm having issues installing citra from l4t megascript and i keep getting this error , logs are attatched please help
[install-fail-Citra.txt](https://github.com/cobalt2727/L4T-Megascript/files/12597845/install-fail-Citra.txt)
Thanks alot

**Comment by cobalt2727** [comment]
Please report this _to the Citra devs_ as I suggested earlier on Discord. You can get in touch with them here https://citra-emu.org/discord/
