### ISSUE TITLE
last question about removing unused programs or fix broken ones, should indicate thats strongly advised to do it.

### ISSUE THREAD

**Issue by pepepaco** [cobalt2727/L4T-Megascript#142]
clicking No leave the machine in very broken state, I spend hours trying to figure why the performance was so bad , reinstalled ubuntu then the Mega script but this time i click Yes and everything's is fine now.

**Comment by cobalt2727** [comment]
...that really shouldn't help performance issues, but hey, if it does somehow for you I'm not complaining
