### ISSUE TITLE
Unable to install MultiMC on RPi5 with Ubuntu Desktop 23.10

### ISSUE THREAD

**Issue by jkulvich** [cobalt2727/L4T-Megascript#150]
[install-fail-scripts-games_and_emulators-minecraft_java_multimc.sh.log](https://github.com/cobalt2727/L4T-Megascript/files/15018037/install-fail-scripts-games_and_emulators-minecraft_java_multimc.sh.log)

**Comment by theofficialgman** [comment]
MultiMC is not a supported script.
https://github.com/cobalt2727/L4T-Megascript/commit/4cfeda568c15ef04f78c37b64dbf8d2998f5a201

**Comment by cobalt2727** [comment]
Yeah, we hid it from the UI a while ago for a reason - I've moved the script to the archive folder just to clear up any confusion.

Here's a list of (Fabric) mods we'd recommend for performance enhancements and controller support - just skip the ones not supported by the current version of Minecraft. Last commit was 2 years ago but I'd still say this list is good today.
https://github.com/cobalt2727/L4T-Megascript/blob/master/assets/MultiMC/megascript-mods.txt
