### ISSUE TITLE
Moonlight does not recognize the pro grip cross keys

### ISSUE THREAD

**Issue by Peter-Fy** [cobalt2727/L4T-Megascript#155]
When I bluetooth the pro grip and use moonlight streaming, the cross keys don't work!

**Comment by cobalt2727** [comment]
Did you remember to press the Screenshot key to toggle off the mouse controls?

If you've already done that, then this should be reported at https://github.com/moonlight-stream/moonlight-qt/issues

**Comment by Peter-Fy** [comment]
Ok. I will reported it at moonlight-qt, Thanks
