### ISSUE TITLE
CSE2-Tweaks

### ISSUE THREAD

**Issue by calvarado194** [cobalt2727/L4T-Megascript#66]
There are two issues regarding your current support for CSE2-Tweaks.

One, Clownacy is not the developler of Tweaks. He is the main developer of CSE2, but at the moment, I'm the sole developer of Tweaks, which is forked from CSE2.

Two, if your script relies on the current GitHub repo, all CSE2 repos and all of its forks (Tweaks included) are currently down as Nicalis (owner of the IP for Cave Story) has hit all of them with a DMCA takedown notice.

**Comment by Lang-Kasempo** [comment]
1) Oh, good to know. We are gonna change it then
2) We know about the takedown and we put a note in the script

**Comment by cobalt2727** [comment]
> There are two issues regarding your current support for CSE2-Tweaks.
> 
> One, Clownacy is not the developler of Tweaks. He is the main developer of CSE2, but at the moment, I'm the sole developer of Tweaks, which is forked from CSE2.
> 
> Two, if your script relies on the current GitHub repo, all CSE2 repos and all of its forks (Tweaks included) are currently down as Nicalis (owner of the IP for Cave Story) has hit all of them with a DMCA takedown notice.

what's the legal situation with this repo? seems untouched - is that just because Nicalis hasn't noticed it yet?
https://github.com/EwanGreen4/CSE2EX

**Comment by calvarado194** [comment]
@cobalt2727 Yea, Nicalis managed to miss quite a few it seems. 

Current legal situation is that CSE2 is allowed to exist as long as code is not publicly shared - this is not ifficial policy but it seems to be what Nicalis is enforcing. Some repos such as that one were indeed missed, and it seems Nicalis has no intention to push it any further. 

the main CSE2 project has been abandoned, to the best of my understanding. My own forked (rebranded as Cave Story: Tweaked) has recently restarted development.

**Comment by cobalt2727** [comment]
What about https://github.com/nxengine/nxengine-evo? This looks like a good replacement, unless we just want to stick with the download RetroPie provides [from libretro](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-nxengine.sh).

**Comment by cobalt2727** [comment]
> the main CSE2 project has been abandoned, to the best of my understanding. My own forked (rebranded as Cave Story: Tweaked) has recently restarted development.

@calvarado194 is this publicly available anywhere?
