### ISSUE TITLE
Bash: 404:: command not found - Option 3: Dolphin

### ISSUE THREAD

**Issue by claytonsulby** [cobalt2727/L4T-Megascript#90]
Selecting 3rd option, Dolphin, ends immediately with `bash: 404:: command not found`
I have run initial setup and I am using Ubuntu 3.3.0 fresh install with Hatake.

**Comment by cobalt2727** [comment]
Huh, could have sworn I commented that line out...
Those options currently aren't ready yet, but I'll try and get them working eventually. PrimeHack will build with the same steps as mainline Dolphin, just using a different repository (I just haven't tested decent configurations yet), Project+ will be up and running when I get around to figuring out their appimage build system, and we should be able to make Slippi build correctly when they switch from using Ishiiruka to mainline as a base.

**Comment by claytonsulby** [comment]
Only a matter of time then!
