### ISSUE TITLE
Switchroot v3.4.0 | Apps not Compiling (Fresh Install)

### ISSUE THREAD

**Issue by Th3Alic3** [cobalt2727/L4T-Megascript#93]
OS: ubuntu 18.04 LTS
Switchroot: ubuntu v3.4.0 (2021-07-23 v2 FRESH INSTALL)
Megascript: "3.4.0 Update Files" (Method A)

Apps "installed" with Megascript but not installed:
- Dolphin
- MelonDS
- Citra
- RetroPie _(currently attempting)_

This is the first time using Ubuntu on my Switch. I am not new to Ubuntu but the Switch is new territory for me. The OS updated perfectly fine. L4T Megascript also install via the microSD load perfectly. 

The L4T Megascript however does not appear to be functioning properly. The emulator applications appear to have loaded the installations but the folders' contents appear to be uncompiled applications and the application commands in terminal cannot find the apps as installed.

From what I observed, with the above mentioned applications, the scripts did not BUILD any of the applications. From all the video tutorials that I have seen posted involving Switchroot: ubuntu v3.3.0 it appears as if they should had on their own.

_(I am hoping that was all that was missed cause Dolphin took forever to download.)_

**Comment by Th3Alic3** [comment]
> Which ones are failing to build?

So far Melon, Citra, and Dolphin.

**Comment by cobalt2727** [comment]
Alright, let's try Dolphin individually as a test. Can you paste this into a terminal then send all the lines it spits back out at you here? It might take a while to build
`bash <( curl https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/helper.sh ) "scripts/games_and_emulators/dolphin/main.sh"`

**Comment by cobalt2727** [comment]
Sounds good. It's late where I am, so I may not get back to you until the morning

**Comment by theofficialgman** [comment]
retropie should be pretty fast (probably 10-15 minutes with good internet)
on switch it only has to build emulationstation, and retroarch
everything else is a binary download which will be fast

**Comment by cobalt2727** [comment]
I'm running into the same error on my Jetson Nano - looks like this is a Dolphin issue. I'll let one of the devs know

**Comment by cobalt2727** [comment]
Try and get Citra and melonDS logs posted if possible

`bash <( curl https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/helper.sh ) "scripts/games_and_emulators/melonds.sh"`

`bash <( curl https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/helper.sh ) "scripts/games_and_emulators/citra.sh"`

**Comment by Th3Alic3** [comment]
I installed "Themes" from the Megascript then Citra and melonDS magically appeared.

**Comment by cobalt2727** [comment]
Dolphin should now build correctly:
https://github.com/JosJuice/dolphin/commit/76324b5e2dd892b17270c504a85a27a4e0e9125c

**Comment by cobalt2727** [comment]
A fix should be ready as soon as this is merged
https://github.com/dolphin-emu/dolphin/pull/10168
