### ISSUE TITLE
MultiMC script doesn't work

### ISSUE THREAD

**Issue by rbits0** [cobalt2727/L4T-Megascript#96]
When I try to run the MultiMC script, it says
```
get_system: command not found
Error: your cpu architecture () is not supported by MultiMC and will fail to compile
```

On L4T Ubuntu Bionic

**Comment by rbits0** [comment]
Nevermind, I guess I needed to run it through the megascript application

**Comment by cobalt2727** [comment]
For future reference, the `helper.sh` script is designed for exactly this kind of thing - there's some documentation for it at the bottom of the file

**Comment by theofficialgman** [comment]
There is also documentation in the wiki for how to use it
